language: python

dist: xenial
sudo: false

services:
  - xvfb # For mayavi headless

matrix:
  include:
    - os: linux
      env: DISTRIB="ubuntu" PYTHON_VERSION="2.7"
      addons:
        apt:
          packages:
            - python-numpy
            - python-matplotlib
            - python-scipy
            - python-pip
            - python-coverage
            - cython
            - python-pandas
    # This environment tests is for mayavi
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="2.7" INSTALL_MAYAVI="true"
    # This environment tests the Python 3 versions
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.4"
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.5"
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.6"
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="2.7" LOCALE=C
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.6" LOCALE=C
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.7" LOCALE=C
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.6" SPHINX_VERSION="dev"
      if: type = cron
    - python: "nightly"
      env: PYTHON_VERSION="nightly"
      os: linux
      addons:
        apt:
          packages:
            libblas-dev
            liblapack-dev
            gfortran
  allow_failures:
    - python: "nightly"

before_install:
  # Make sure that things work even if the locale is set to C (which
  # effectively means ASCII). Some of the input rst files have unicode
  # characters and we need to deal with this gracefully.
  - |
    if [[ $LOCALE == C ]]; then
        export LC_CTYPE=C
        export LC_ALL=C
        export LANG=C
    fi

install:
  - source continuous_integration/travis/install.sh

script:
  - bash continuous_integration/travis/test_script.sh

after_success:
  - pip install codecov
  - codecov
