language: python

env:
    - PYTHON_VERSION="2.7"
    - PYTHON_VERSION="3.4"

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create --yes -n testenv python=$PYTHON_VERSION pip matplotlib nose
      pillow coverage sphinx
    - source activate testenv
    - python setup.py install

script:
    - python setup.py nosetests
