language: python
sudo: false
addons:
  apt:
    packages:
    - xvfb # For mayavi headless

virtualenv:
        system_site_packages: true

matrix:
  include:
    - os: linux
      env: DISTRIB="ubuntu" PYTHON_VERSION="2.7"
      addons:
        apt:
          packages:
            - python-numpy
            - python-matplotlib
            - python-scipy
            - python-pip
            - python-coverage
            - cython
            - python-pandas
    # This environment tests is for mayavi
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="2.7"
    # This environment tests the Python 3 versions
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.4"
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.5"
    - os: linux
      env: DISTRIB="conda" PYTHON_VERSION="3.6"
    - os: linux
      dist: trusty
      python: 'nightly'
  allow_failures:
    - python: "nightly"

before_install:
    - if [ "$DISTRIB" == "conda" ]; then
         wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
         chmod +x miniconda.sh;
         ./miniconda.sh -b;
         export PATH=/home/travis/miniconda2/bin:$PATH;
         conda update --yes conda;
      fi

install:
    # force no mkl because mayavi requires old version of numpy
    # which then crashes with pandas and seaborn
    - if [ "$DISTRIB" == "conda" ]; then
        conda create --yes -n testenv python=$PYTHON_VERSION pip nomkl numpy
        setuptools matplotlib pillow sphinx pytest pytest-cov coverage seaborn;
        source activate testenv;
        if [ "$PYTHON_VERSION" == "2.7" ]; then
          conda install --yes mayavi;
        fi;
      fi;
    - |
      if [ "$DISTRIB" == "ubuntu" ]; then
        # Use a separate virtual environment than the one provided by
        # Travis because it contains numpy and we want to use numpy
        # from apt-get
        deactivate
        virtualenv --system-site-packages testvenv
        source testvenv/bin/activate
        pip install -U requests[security]  # ensure SSL certificate works
        pip install -r requirements.txt
        pip install seaborn sphinx==1.5.5 pytest pytest-cov
      fi
    - python setup.py install

# To test the mayavi environment follow the instructions at
# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
    - python setup.py test
    - pytest sphinx_gallery
    - cd doc
    - make html-noplot
    - make html -j 2
