
# CI on Windows via appveyor
# This file was based on Olivier Grisel's python-appveyor-demo

environment:

  global:
    PYTHON: "C:\\conda"
    CONDA_DEPENDENCIES: numpy seaborn statsmodels "matplotlib<3.2.1|>3.2.2" sphinx pillow pytest pytest-cov sphinx_rtd_theme joblib plotly
    PIP_DEPENDENCIES: ipython"

  matrix:
    - PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
    - PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"

platform:
    -x64

install:
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "conda activate test"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - python setup.py develop
  - pytest --tb=short sphinx_gallery
  # Build the docs
  - cd doc
  # The Makefile doesn't work directly on Windows PowerShell because of
  # slashes (but will work e.g. in Msys-git), so for now do these manually
  # make html-noplot
  - sphinx-build -D plot_gallery=0 -b html -d _build\doctrees . _build\html
  # make html
  - sphinx-build -b html -d _build\doctrees . _build\html

artifacts:
  - path: doc\_build\html
